# Generated by Django 3.1.2 on 2020-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoboard',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
